apiVersion: batch/v1
kind: CronJob
metadata:
  name: bombardier
  namespace: challenge
spec:
  schedule: "* * * * *"
  suspend: true
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: go-binaries
              emptyDir: {}
          initContainers:
            - name: bombardier-install
              image: golang:1.20
              imagePullPolicy: IfNotPresent
              command:
                - go
                - install
                - github.com/codesenberg/bombardier@v1.2.5
              volumeMounts:
                - name: go-binaries
                  mountPath: /go/bin
          containers:
            - name: golang
              image: golang:1.20
              imagePullPolicy: IfNotPresent
              command:
                - bombardier
              args:
                - -c
                - $(MAX_CONNECTIONS)
                - -n
                - $(NUM_REQUESTS)
                - $(TARGET_URL)
              env:
                - name: MAX_CONNECTIONS
                  value: "60"
                - name: NUM_REQUESTS
                  value: "100000"
                - name: TARGET_URL
                  value: http://java-backend.challenge.svc.cluster.local/test
              volumeMounts:
                - name: go-binaries
                  mountPath: /go/bin
          restartPolicy: Never
      backoffLimit: 5
