apiVersion: batch/v1
kind: Job
metadata:
  name: bombardier
spec:
  template:
    spec:
      volumes:
        - name: go-packages
          emptyDir: {}
      initContainers:
        - name: bombardier-install
          image: golang:1.20
          imagePullPolicy: IfNotPresent
          command:
            - go install github.com/codesenberg/bombardier@v1.2.5
          volumeMounts:
            - name: go-packages
              mountPath: /go/pkg
      containers:
        - name: golang
          image: golang:1.20
          imagePullPolicy: IfNotPresent
          command:
            - bombardier -c $MAX_CONNECTIONS -n $NUM_REQUESTS $TARGET_URL
          env:
            - name: MAX_CONNECTIONS
              value: "100"
            - name: NUM_REQUESTS
              value: "10000"
              restartPolicy: OnFailure
            - name: TARGET_URL
              value: http://java-backend.challenge.svc.cluster.local
          volumeMounts:
            - name: go-packages
              mountPath: /go/pkg
      restartPolicy: Never
  backoffLimit: 5
